### ISSUE TITLE
关于hyperopt中fmin的一个错误问题

### ISSUE THREAD

**Issue by AAAAAA128** [FontTian/hyperopt-doc-zh#1]
您好，首先感谢您翻译hyperopt的工作，这对于国内的用户是一个十分有帮助的工作，可是在我使用hyperopt的过程中遇到一个问题，搜索了很多资料人就无法解决，希望作者可以给与帮助，谢谢，问题如下：
我按照fmin文档的代码在我的python环境中执行了以后，出现了一个错误提示，代码和错误如下
`from hyperopt import fmin, tpe, hp

space = hp.uniform('x', -10, 10)
best = fmin(fn=lambda x : x**2,
            space=space,
            algo=tpe.suggest,
            max_evals=100)

print(dir(best))`

>  File "D:\Anaconda3\lib\site-packages\hyperopt\fmin.py", line 314, in fmin
    pass_expr_memo_ctrl=pass_expr_memo_ctrl)
  File "D:\Anaconda3\lib\site-packages\hyperopt\base.py", line 786, in __init__
    pyll.toposort(self.expr)
  File "D:\Anaconda3\lib\site-packages\hyperopt\pyll\base.py", line 715, in toposort
    assert order[-1] == expr
TypeError: 'generator' object is not subscriptable

**Comment by AAAAAA128** [comment]
你好，问题已解决。https://blog.csdn.net/boyuancong/article/details/79562852

**Comment by TianFengshou** [comment]
很抱歉,没有及时回复,但是很有趣的是给你解答的这篇文章正是转载的我的博客.或许这也算是一种缘分吧.lol

**Comment by AAAAAA128** [comment]
再次对您的工作表示感谢，对国内人员十分有帮助。

**Comment by TianFengshou** [comment]
：）客气了
